name: 'Build'
variables:
  build_number: '$(Build.BuildNumber)'
  commit_id: '$(Build.SourceVersion)'

trigger:
  branches:
    include:
    - '*'

jobs:
- job: Build
  timeoutInMinutes: 100
  steps:
  - task: Bash@3
    displayName: 'Test Application'
    inputs:
      targetType: inline
      script: |
          cd notejam/spring
          mvn test

  - task: CopyFiles@1
    displayName: 'Copy Files'
    inputs:
      SourceFolder: '$(build.sourcesdirectory)'

      Contents: |
        **

      TargetFolder: '$(build.artifactstagingdirectory)'
  
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifacts'
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)'

